### ISSUE TITLE
Script sanitizePasswordDump.sh

### ISSUE THREAD

**Issue by Skullack** [outflanknl/PasswordDump2ELK#1]
Hi 

the script sanitizePasswordDump.sh hangs after "Connection to 127.0.0.1 3515 port [tcp/*] succeeded!"

also when giving the *.txt in the folder as part of the command it only uses the first txt file and does not go beyond that. 

Is there a way to start importing all files in the given folder. 

Looking forward to your assistance
G

**Comment by MarcOverIP** [comment]
Hi,

This code is very old and I don't have the time to perform troubleshooting, or make changes. My first guess is that the script doesn't hang, but that it is actually working.

For any further troubleshooting, I recommend to read the code. It is readable shell scripting. Good luck!

**Comment by Skullack** [comment]
Dont worry I changed the script 

changed to the following
echo "[+] Sending to Logstash"
cat /tmp/sanitized2$FILENAME | nc -v 127.0.0.1 3515 **| echo '{"succeeded!": true}' | sudo nc -N 127.0.0.1 3515**
